[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
lockfun = "GaVb9PQr9eTnFe6zVAKwUyfCCDbp7dR1KqdJrFnQRexQ"

[programs.devnet]
lockfun = "GaVb9PQr9eTnFe6zVAKwUyfCCDbp7dR1KqdJrFnQRexQ"

[programs.localnet]
lockfun = "GaVb9PQr9eTnFe6zVAKwUyfCCDbp7dR1KqdJrFnQRexQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
